Repository Bjorgeh/rapportsystem-backend, pull requests merged in 2023-11, with the labels that each got.

#33 Fixed gitignore, README file and more
  .gitignore
  .vscode/settings.json
  Models/__init__.py
  Models/__pycache__/__init__.cpython-312.pyc
  Models/__pycache__/user_model.cpython-312.pyc
  PW_hashHandler/__pycache__/pw_manager.cpython-312.pyc
  README.md
  SQLAdminConnections/__init__.py
  SQLAdminConnections/__pycache__/SQL_AdminConnector.cpython-312.pyc
  SQLAdminConnections/__pycache__/SQL_AdminQuerys.cpython-312.pyc
  SQLAdminConnections/__pycache__/SQL_CreateNewAdminUser.cpython-312.pyc
  SQLAdminConnections/__pycache__/SQL_CreateNewLeaderUser.cpython-312.pyc
  SQLAdminConnections/__pycache__/SQL_CreateNewOperatorUser.cpython-312.pyc
  SQLAdminConnections/__pycache__/__init__.cpython-312.pyc
  SQLConnections/__init__.py
  SQLConnections/__pycache__/__init__.cpython-312.pyc
  SQLConnections/__pycache__/secret.cpython-312.pyc
  USER_obj/__init__.py
  USER_obj/__pycache__/__init__.cpython-312.pyc
  USER_obj/__pycache__/new_user.cpython-312.pyc
  USER_obj/__pycache__/users.cpython-312.pyc
  USER_session/__init__.py
  USER_session/__pycache__/__init__.cpython-312.pyc
  USER_session/__pycache__/sessionhandler.cpython-312.pyc
  authorization/__init__.py
  authorization/__pycache__/__init__.cpython-312.pyc
  authorization/__pycache__/apiKeyAuth.cpython-312.pyc
  authorization/__pycache__/api_key.cpython-312.pyc
  authorization/__pycache__/login_validation.cpython-312.pyc
  authorization/__pycache__/session_config.cpython-312.pyc
Labels: bug

#42 Response code and sample API input values
  .gitignore
  .vscode/settings.json
  Models/user_model.py
  Requests/POST_R/login.py
Labels: enhancement

#50 Update README.md
  README.md
Labels: documentation

#53 Token remake
  API.py
  Common/Requirements/admin_req.py
  Common/Requirements/session_req.py
  Common/Requirements/valid_token.py
  README.md
  Requests/GET_R/logout.py
  Requests/GET_R/test.py
  Requests/GET_R/test_admin.py
  Requests/GET_R/userActivity.py
  Requests/POST_R/createUser.py
  Requests/POST_R/deleteUser.py
  Requests/POST_R/login.py
  Requests/POST_R/updatePassword.py
  SQLAdminConnections/SQL_AdminQuerys.py
  SQL_setup/userdatabase.sql
  USER_session/sessionhandler.py
  USER_session/tokenHandler.py
Labels: enhancement
